import {
  Users,
  Plus,
  User,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Settings,
  Download,
  Search,
  X,
  ArrowUpDown,
  Filter,
  Group,
  Lock,
  Trash2,
  Camera,
  Mic,
  Sparkles,
  Paperclip,
  Type,
  FileText,
  MessageSquare,
  MessageCircle,
  Edit3,
  PenTool,
  UserPlus,
} from 'lucide-react';

export const ICONS = {
  GROUPS: Users,
  ADD: Plus,
  PROFILE: User,
  BACK: ChevronLeft,
  CHEVRON_RIGHT: ChevronRight,
  CHEVRON_DOWN: ChevronDown,
  SETTINGS: Settings,
  DOWNLOAD: Download,
  SEARCH: Search,
  CLOSE: X,
  SORT: ArrowUpDown,
  FILTER: Filter,
  GROUPING: Group,
  LOCK: Lock,
  DELETE: X,
  CAMERA: Camera,
  MIC: Mic,
  SPARKLES: Sparkles,
  PAPERCLIP: Paperclip,
  TYPE: Type,
  FILE_TEXT: FileText,
  MESSAGE: MessageSquare,
  MESSAGE_CIRCLE: MessageCircle,
  EDIT: Edit3,
  PEN: PenTool,
  INVITE: UserPlus,
};
